### ISSUE TITLE
Training error: `RuntimeError: CUDA error: an illegal memory access was encountered`

### ISSUE THREAD

**Issue by saryazdi** [czczup/ViT-Adapter#77]
Hi, thanks for the great work and releasing the code!

I want to finetune ViT-adapter but am running into `RuntimeError: CUDA error: an illegal memory access was encountered`.

Inference works fine, this error just pops up when trying to do backprop.

I'd greatly appreciate any hints on what might be going wrong. Thank you!
1. **The code:**
```python3
import mmcv
from mmcv.runner import load_checkpoint
from mmseg.models import build_segmentor
from mmcv.cnn.utils import revert_sync_batchnorm
import mmseg_custom
import torch
from tqdm import tqdm

VIT_ADAPTER_CONFIG = "/path/to/ViT-Adapter/segmentation/configs/coco_stuff164k/mask2former_beit_adapter_large_896_80k_cocostuff164k_ss.py"
VIT_ADAPTER_CHECKPOINT = "/path/to/mask2former_beit_adapter_large_896_80k_cocostuff164k.pth.tar"
def init_segmentor_finetune(config, checkpoint=None):
    if isinstance(config, str):
        config = mmcv.Config.fromfile(config)
    elif not isinstance(config, mmcv.Config):
        raise TypeError('config must be a filename or Config object, '
                        'but got {}'.format(type(config)))
    config.model.pretrained = None
    model = build_segmentor(
        config.model,
        train_cfg=config.get('train_cfg'),
        test_cfg=config.get('test_cfg')
    )
    if checkpoint is not None:
        checkpoint = load_checkpoint(model, checkpoint, map_location='cpu')
        if 'CLASSES' in checkpoint.get('meta', {}):
            model.CLASSES = checkpoint['meta']['CLASSES']
    model.cfg = config  # save the config in the model for convenience
    model = revert_sync_batchnorm(model)
    return model

class MinimalViTAdapter(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.vit_adapter = init_segmentor_finetune(VIT_ADAPTER_CONFIG, VIT_ADAPTER_CHECKPOINT)

    def forward(self, x):
        assert x.shape[-1] == x.shape[-2] == 896
        img_metas = [{'ori_shape': (896, 896, 3)}] * x.shape[0]
        return self.vit_adapter.encode_decode(img=x, img_metas=img_metas)

if __name__ == "__main__":
    model = MinimalViTAdapter()
    model = model.cuda()
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
    x = torch.randn(2, 3, 896, 896).cuda()
    # dummy training
    for i in tqdm(range(100)):
        y = model(x)
        loss = y.sum().abs()
        print(loss)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
```
2. **The error log:**
```bash
tensor(8042538.5000, device='cuda:0', grad_fn=<AbsBackward0>)
  0%|                                                                                                                                                                                                                                                                                                                                                 | 0/100 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/random.py", line 125, in fork_rng
    yield
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 130, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/path/to/ViT-Adapter/segmentation/mmseg_custom/models/backbones/adapter_modules.py", line 110, in _inner_forward
    attn = self.attn(self.query_norm(query), reference_points,
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/path/to/ViT-Adapter/segmentation/ops/modules/ms_deform_attn.py", line 99, in forward
    assert (input_spatial_shapes[:, 0] *
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minimal_vit_adapter.py", line 55, in <module>
    loss.backward()
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py", line 130, in backward
    outputs = ctx.run_function(*detached_inputs)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/dist-packages/torch/random.py", line 129, in fork_rng
    torch.cuda.set_rng_state(gpu_rng_state, device)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/random.py", line 64, in set_rng_state
    _lazy_call(cb)
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 155, in _lazy_call
    callable()
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/random.py", line 62, in cb
    default_generator.set_state(new_state_copy)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```
3. **The environment:**
```bash
torch==1.11.0+cu115
mmcv-full==1.4.7
mmdet==2.22.0
mmsegmentation==0.20.2
```

**Comment by saryazdi** [comment]
**Update**: Trying to run `dist_train.sh` also yields a similar error:
```bash
/home/soroush/.local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/home/soroush/.local/lib/python3.8/site-packages/torch/nn/functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
/home/soroush/.local/lib/python3.8/site-packages/torch/nn/functional.py:3657: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
/home/soroush/.local/lib/python3.8/site-packages/torch/nn/functional.py:3657: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 
  warnings.warn(
/home/soroush/.local/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
/home/soroush/.local/lib/python3.8/site-packages/torch/_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /pytorch/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
error in ms_deformable_col2im_cuda: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from query at /pytorch/aten/src/ATen/cuda/CUDAEvent.h:95 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f2e83b58a22 in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x132 (0x7f2f28f44262 in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x50 (0x7f2f28f45ec0 in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x11c (0x7f2f28f468dc in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xd6de4 (0x7f2f29b06de4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f2f2e73d609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f2f2e877133 in /usr/lib/x86_64-linux-gnu/libc.so.6)

error in ms_deformable_col2im_cuda: an illegal memory access was encountered
Traceback (most recent call last):
  File "./train.py", line 215, in <module>
    main()
  File "./train.py", line 204, in main
    train_segmentor(
  File "/home/soroush/.local/lib/python3.8/site-packages/mmseg/apis/train.py", line 167, in train_segmentor
    runner.run(data_loaders, cfg.workflow)
  File "/home/soroush//home/soroush/mmcv/mmcv/runner/iter_based_runner.py", line 134, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/soroush//home/soroush/mmcv/mmcv/runner/iter_based_runner.py", line 67, in train
    self.call_hook('after_train_iter')
  File "/home/soroush//home/soroush/mmcv/mmcv/runner/base_runner.py", line 309, in call_hook
    getattr(hook, fn_name)(self)
  File "/home/soroush//home/soroush/mmcv/mmcv/runner/hooks/optimizer.py", line 56, in after_train_iter
    runner.outputs['loss'].backward()
  File "/home/soroush/.local/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/soroush/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::CUDAError'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from query at /pytorch/aten/src/ATen/cuda/CUDAEvent.h:95 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f3b99e23a22 in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10d::ProcessGroupNCCL::WorkNCCL::finishedGPUExecutionInternal() const + 0x132 (0x7f3c3f20f262 in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::isCompleted() + 0x50 (0x7f3c3f210ec0 in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: c10d::ProcessGroupNCCL::workCleanupLoop() + 0x11c (0x7f3c3f2118dc in /home/soroush/.local/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xd6de4 (0x7f3c3fdd1de4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #5: <unknown function> + 0x8609 (0x7f3c44a08609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: clone + 0x43 (0x7f3c44b42133 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

**Comment by saryazdi** [comment]
For anyone who might be facing this in the future: Solved by downgrading to `mmcv-full==1.4.2`. That also required me to downgrade to `torch==1.9.0` because `mmcv` expected [THC.h](https://github.com/open-mmlab/mmdetection3d/issues/1332) file to be there.
Also: I made sure cuda runtime version (`nvcc --version`) is the same as torch cudatools version (`pip3 show torch`)

**Comment by czczup** [comment]
Thanks for your feedback!
